### ISSUE TITLE
Font Collector Problem

### ISSUE THREAD

**Issue by moefangsubs** [TypesettingTools/Aegisub#281]
I have been using Aegisub for my subtitle work on my Windows 10 , and recently encountered an issue with the **Font Collector** feature. I was trying to collect fonts using the "_copy fonts to folder"_ option, but after selecting it, the program displayed a message saying "_Updating font cache_." However, shortly after, Aegisub force-closed without any further explanation.

I decided to try other options, such as "check font for availability" and "copy fonts to zipped archive," but each attempt resulted in the same issue. I searched online to see if others were facing the same problem, hoping to find a solution, but was unable to find anything related.

At this point, I am left wondering if there is an issue with my system or if this is a bug within Aegisub itself. Any insight into this would be greatly appreciated.

**Comment by arch1t3cht** [comment]
Can you check if this also happens with 3.4.2, which was released yesterday? At least one crash relating to the fonts collector was fixed there.

**Comment by moefangsubs** [comment]
Thank you for your response. 

I have just updated Aegisub from version 3.4.1 to 3.4.2, but the issue still occurs. 
Fortunately, I realized that version 3.2.2 is still installed on my PC, and when I tested Font Collector there, it worked without any issues. For now, I will continue using the older version until a more stable update is available.

**Comment by arch1t3cht** [comment]
Probably fixed after the font collector rework in dc7d3c5db7d25d11d723fe9752574957bc245128, the font collector now no longer needs to build a font cache.
